// angular-source/src/app/google/google.component.ts
import { Component, Input } from '@angular/core';

import { GoogleService, SearchResults, SearchType } from '../services/google.service';
import { BemClassPipe } from '../shared/bemClass.pipe';

@Component({
	selector: 'res-google',
	templateUrl: './google.component.html',
	styleUrls: ['./google.component.css']
})
export class GoogleComponent {

	searchTerm:string;

	textSearchResults:SearchResults;
	imageSearchResults:SearchResults;

	constructor(private service:GoogleService){}

	private showTextResults(results:SearchResults) {
		this.textSearchResults = results;
	}

	private showImageResults(results:SearchResults) {
		this.imageSearchResults = results;
	}

	updateSearch(searchTerm:string) {
		this.searchTerm = searchTerm;
		this.textSearchResults = null;
		this.imageSearchResults = null;

		const textSetter = results => {this.textSearchResults = results;};
		const imageSetter = results => {this.imageSearchResults = results;};

		this.service.getTextResults(searchTerm).subscribe(textSetter, textSetter);
		this.service.getImageResults(searchTerm).subscribe(imageSetter, imageSetter);
	}
}

<div class="google">
	<h1 class="title">Search via Google APIs Using Angular</h1>
	<p class="description">This page is built using Angular to retrieve the first 10 search and image results from Google. The source files are accessible <a href="../angular-source" class="link">here</a>.</p>
	<res-query (search)="updateSearch($event)"></res-query>

	<div *ngIf="searchTerm" class="results">
		<h2 class="results-title">Results for “{{ searchTerm }}”</h2>
		<div class="column"><res-results [results]="textSearchResults" type="text"></res-results></div>
		<div class="column"><res-results [results]="imageSearchResults" type="image"></res-results></div>
	</div>
</div>

// react-source/src/Components/Google/Google.js
import React from 'react';
import UtilityMethods from '../../common';

import Query from './Query';
import Results from './Results';

import './Google.css';

const
	block = 'c-google',
	resultsElementBase = 'results',
	columnClass = UtilityMethods.bemClass(block, resultsElementBase + '-column')
;

function Google({query, imageJson, textJson, queryDispatch}) {

	return (
		<div className={ UtilityMethods.bemClass(block, null, (query ? null : 'initial') ) }>
			<h1 className={ UtilityMethods.bemClass(block, 'title') }>Search via Google APIs Using React</h1>
			<p className={ UtilityMethods.bemClass(block, 'description') }>This page is built using React and Redux to retrieve the first 10 search and image results from Google. The source files are accessible <a href="../react-source" className={UtilityMethods.bemClass(block, 'link')}>here</a>.</p>
			<Query block={block} query={query} queryDispatch={queryDispatch}/>
			{
				query && (
					<div className={ UtilityMethods.bemClass(block, resultsElementBase) }>
						<h2 className={ UtilityMethods.bemClass(block, resultsElementBase + '-title') }>Results for “{query}”</h2>
						<div className={columnClass}><Results block={block} elementBase={resultsElementBase} type='text' json={textJson}/></div>
						<div className={columnClass}><Results block={block} elementBase={resultsElementBase} type='image' json={imageJson}/></div>
					</div>
				)
			}
		</div>
	);
}

export default Google;
